version: '3'
services:
  TomcatBilling:
    container_name: TomcatBilling
    image: tomcat:9.0-jdk11-corretto-al2
    restart: always
    hostname: 172.17.0.2
    ports:
      - "8088:8080"
    volumes:
    - C:/Billing_Manager/setup:/usr/local/setup
    - C:/Billing_Manager/BillBook:/usr/local/BillBook
    - C:/Billing_Manager/BillBook/temp:/usr/local/BillBook2/temp
    command: sh -c "mkdir -p /usr/local/BillBook && mkdir -p /usr/local/BillBook2/temp && mkdir -p /usr/local/setup && cp /usr/local/setup/Billing_Manager.war /usr/local/tomcat/webapps/Billing_Manager.war && catalina.sh run && java -jar /usr/local/setup/MonitorDirectory.jar "
  MongoBilling:
    container_name: MongoBilling
    environment:
      MONGO_INITDB_DATABASE: billing
    image: mongo:latest
    restart: always
    hostname: localhost
    ports:
      - "26017:27017"
    volumes:
        - C:/Billing_Manager/setup:/usr/local/setup
        - C:/Billing_Manager/setup:/docker-entrypoint-initdb.d
networks:
  default:
    driver: bridge